version: '3'
services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=Testing123!
      - POSTGRES_DB=test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
